### ISSUE TITLE
Homeassistant integration using ESPHome

### ISSUE THREAD

**Issue by teodorch85** [ecodina/hunter-wifi#2]
Hi!
Thank you for your work!

I am trying to integrate it into my HomeAssistant server but I don't know anything about coding!

I usually use ESPHome esphome.io/ for my other devices and I am trying to import it but with no luck.

Could you please have a look? 
https://esphome.io/custom/custom_component.html

Otherwise, I could use your http API using this guide
https://www.home-assistant.io/integrations/switch.rest/

Thank you,
Theodoros

**Comment by teodorch85** [comment]
With my very little knowledge about coding I managed to get it working.

I added to helper variables
input_select.hunterzone
input_number.huntertimer

I also added this in my configuration.yaml

```
rest_command:
  starthunter:
    url: "http://192.168.1.199/api/start/zone/{{ states('input_select.hunterzone') }}?time={{states('input_huntertimer')}}"
  stophunter:
    url: "http://192.168.1.199/api/stop/zone/{{ states('input_select.hunterzone') }}"

```
